[project]
name = "basic-socket-rpc"
version = "0.2.0"
description = "Basic binary socket based rpc for Python"
readme = "README.md"
requires-python = ">=3.6"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=7.0.1",
]
